[project]
name = "vzd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "envpool>=0.8.4",
    "gymnasium[accept-rom-license, other]==0.27.1",
    "torch",
    "torchvision",
    "termcolor",
    "scipy>= 1.7.0",
    "pynvml==11.5.0",
    "matplotlib==3.6.0",
    "seaborn==0.12.2",
    "huggingface_hub==0.14.1",
    "opencv-python>=4.11.0.86",
    "numpy<2",
]
